### ISSUE TITLE
[FEAT] Ability to add App Description from new UI

### ISSUE THREAD

**Issue by kunal0137** [SEMOSS/community#25]
### Is your feature request related to a problem? Please describe.

We do not have a way to update the app description from the new ui

![image](https://github.com/user-attachments/assets/220a3b2e-f956-4671-a8c4-58fb00b7dbd2)

### Describe the solution you'd like

Be able to edit the description from the Edit app details page

![image](https://github.com/user-attachments/assets/28c13f1f-e57b-42ad-9768-92c22f4d27fd)

![image](https://github.com/user-attachments/assets/157edd67-a09b-473c-b71a-803da18c01ba)

### Describe alternatives you've considered

I tried the main uses section - that doesn't appear on the main screen. You can go through the old ui and edit it there for now
![image](https://github.com/user-attachments/assets/d197be9e-706d-4357-abb7-f429c68acbf2)

### Tasks

A list of individual tasks / issues that need to be completed before the ticket is resolved

- [ ]
- [ ]

**Comment by natdink** [comment]
I also noticed that when you go to Edit App Details page, there is no left hand nav menu anymore. Can the dev please also add that back to this page view?

You can see that the left nav menu is missing.

![Image](https://github.com/user-attachments/assets/c062c958-1424-4ae1-9086-51377ba5a7c5)
