### ISSUE TITLE
[BUG] Cannot publish my app

### ISSUE THREAD

**Issue by levgor360** [SEMOSS/community#36]
### A clear and concise description of what the issue is.
The button "make public" is grayed out both in "Edit App Details" window and in "Open settings" >>> "App Settings". I am able to make any of the apps I've created Discoverable, but not public.

This occurs both when I log in through Microsoft login and via the username and password on the window https://workshop.cfg.deloitte.com/cfg-ai-demo/SemossWeb/packages/client/dist/#/login

#### How to reproduce the issue

1. Go to https://workshop.cfg.deloitte.com/cfg-ai-demo/SemossWeb/packages/client/dist/#/login
2. 
3. On home page click on the triple dots next to an app in which you are an author. 
4. Click on the option "Edit app details" from the options.
5. Scroll down until you see the options "Make Public", "Make Discoverable" and "Delete".

### Expected results

That the toggle "Make Public" is interactive, in full color and offers the availability to be toggled on.

### Actual results
The "Make Public" button is greyed out and non-interactive. 

### Environment

(please complete the following information):

- browser type and version: Google Chrome Version 128.0.6613.139 (Official Build) (64-bit)
- node.js version: `node -v` - n/a

![Screenshot 2](https://github.com/user-attachments/assets/954ed890-9557-4f44-9df2-ba96b8d5de99)
![Screenshot 1](https://github.com/user-attachments/assets/aa3e6f78-02b8-4472-8cbc-6684669c5b3f)

**Comment by saahithisk** [comment]
Specific to the demo environment, only administrators can set projects to be public
